/**
 * Searchable icon + emoji catalog for the IconPicker popover ONLY. Kept out of
 * the lean icon-picker-data module so list/card code that just resolves a stored
 * icon never bundles these keyword strings + the emoji set. Curated (not the full
 * Phosphor library) so the picker stays fast and the bundle small.
 */

import { ICON_BY_NAME, type PhosphorIcon } from "./icon-picker-data";

export type PhosphorEntry = { name: string; Icon: PhosphorIcon; keywords: string };

/** [name, keywords] pairs; the component is resolved from the shared map. */
const ICON_KEYWORDS: Array<[string, string]> = [
  // Documents
  ["FileText", "document file page text agreement"],
  ["File", "document file blank"],
  ["FilePdf", "pdf document file"],
  ["FileDoc", "doc word document file"],
  ["Files", "documents files stack"],
  ["Folder", "folder directory group"],
  ["Note", "note memo card"],
  ["NotePencil", "note edit write form"],
  ["ClipboardText", "clipboard form checklist intake"],
  ["Receipt", "receipt invoice bill"],
  ["Signature", "signature sign esign"],
  ["IdentificationCard", "id identity license w9 card"],
  ["SealCheck", "verified seal approved certified"],
  ["ShieldCheck", "shield insurance protection secure compliance"],
  ["Stamp", "stamp approve permit official"],
  // Property
  ["House", "house home property rental"],
  ["HouseLine", "house home property"],
  ["Buildings", "buildings property portfolio city"],
  ["Storefront", "storefront shop business"],
  ["Key", "key access lock checkin"],
  ["Door", "door entry access"],
  ["Bed", "bed bedroom sleep"],
  ["Bathtub", "bath bathroom tub"],
  ["Couch", "couch sofa living furniture"],
  ["Television", "tv television media"],
  ["Garage", "garage parking"],
  ["Bridge", "bridge location"],
  // Money
  ["CreditCard", "card payment credit authorization"],
  ["Bank", "bank ach account payout"],
  ["Money", "money cash payment"],
  ["Coins", "coins money fee"],
  ["Wallet", "wallet payment balance"],
  ["ChartLine", "chart growth performance revenue"],
  ["ChartBar", "chart stats report"],
  ["Calculator", "calculator finance math"],
  ["Tag", "tag price label"],
  // People + comms
  ["Users", "people team owners guests"],
  ["User", "person owner guest user"],
  ["UserCircle", "profile person avatar"],
  ["HandWaving", "welcome hello greeting onboarding"],
  ["Handshake", "deal agreement partner"],
  ["Smiley", "happy face smile"],
  ["Envelope", "email mail message"],
  ["Phone", "phone call contact"],
  ["ChatCircle", "chat message comment"],
  ["ChatsCircle", "chats messages conversation"],
  ["Megaphone", "announce broadcast notice"],
  ["Bell", "bell notification reminder alert"],
  // Home systems / ops
  ["WifiHigh", "wifi internet network"],
  ["Lightbulb", "light idea electric"],
  ["Thermometer", "temperature thermostat hvac"],
  ["Snowflake", "cold ac cooling winter"],
  ["Fire", "heat fire furnace"],
  ["Drop", "water plumbing leak"],
  ["Plugs", "power outlet electric"],
  ["Wrench", "repair maintenance fix tool"],
  ["Hammer", "build repair construction"],
  ["Toolbox", "tools maintenance setup"],
  ["Broom", "clean cleaning turnover"],
  ["PaintRoller", "paint decor renovate"],
  ["Lightning", "power energy fast action"],
  // Time / place / travel
  ["Calendar", "calendar date schedule booking"],
  ["Clock", "time clock hours"],
  ["MapPin", "location address pin map"],
  ["Compass", "guide explore directions guidebook"],
  ["Car", "car parking transport"],
  ["Airplane", "travel flight trip"],
  ["Suitcase", "luggage travel trip"],
  ["Sun", "sun day weather"],
  ["Moon", "night moon"],
  ["Tree", "tree nature outdoor"],
  ["Leaf", "leaf nature eco green"],
  ["Plant", "plant garden nature"],
  ["Mountains", "mountains nature view"],
  // Food / lifestyle
  ["ForkKnife", "food dining kitchen restaurant"],
  ["Coffee", "coffee cafe breakfast"],
  ["Wine", "wine drink welcome"],
  ["ShoppingCart", "shopping supplies groceries"],
  ["Gift", "gift welcome present"],
  // Misc / status
  ["Star", "star favorite rating review"],
  ["Heart", "heart love favorite"],
  ["Trophy", "trophy award win"],
  ["Target", "target goal focus"],
  ["Flag", "flag milestone mark"],
  ["Bookmark", "bookmark save"],
  ["Books", "books guide manual handbook"],
  ["GraduationCap", "education training onboarding"],
  ["Briefcase", "work business portfolio"],
  ["Camera", "camera photo inspection"],
  ["Image", "image photo picture"],
  ["Lock", "lock secure private"],
  ["LockKey", "lock key secure access code"],
  ["Eye", "view seen preview"],
  ["Gear", "settings config gear"],
  ["Sliders", "settings controls adjust"],
  ["Sparkle", "ai magic sparkle generate"],
  ["Confetti", "celebrate done complete"],
  ["CheckCircle", "done complete approved check"],
  ["Warning", "warning alert caution"],
  ["Info", "info about details"],
  ["PawPrint", "pet pets policy animal"],
  ["Dog", "dog pet animal"],
];

export const PHOSPHOR_ICONS: PhosphorEntry[] = ICON_KEYWORDS.map(([name, keywords]) => ({
  name,
  Icon: ICON_BY_NAME[name],
  keywords,
}));

export type EmojiEntry = { char: string; keywords: string };
export type EmojiGroup = { label: string; emojis: EmojiEntry[] };

/** Curated emoji set grouped by category — covers the property/ops domain. */
export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: "Property",
    emojis: [
      { char: "🏠", keywords: "house home property" },
      { char: "🏡", keywords: "house garden home" },
      { char: "🏘️", keywords: "houses neighborhood" },
      { char: "🏚️", keywords: "house old" },
      { char: "🏢", keywords: "building office" },
      { char: "🏨", keywords: "hotel rental" },
      { char: "🏖️", keywords: "beach vacation" },
      { char: "🛏️", keywords: "bed bedroom" },
      { char: "🛋️", keywords: "couch living" },
      { char: "🚪", keywords: "door entry" },
      { char: "🔑", keywords: "key access" },
      { char: "🗝️", keywords: "key old access" },
      { char: "🧹", keywords: "broom clean turnover" },
      { char: "🧽", keywords: "sponge clean" },
      { char: "🪑", keywords: "chair furniture" },
      { char: "🚿", keywords: "shower bathroom" },
    ],
  },
  {
    label: "Documents",
    emojis: [
      { char: "📄", keywords: "document page file" },
      { char: "📃", keywords: "document curl page" },
      { char: "📝", keywords: "memo form write" },
      { char: "📋", keywords: "clipboard checklist" },
      { char: "📑", keywords: "tabs bookmark documents" },
      { char: "🗂️", keywords: "folder dividers files" },
      { char: "📁", keywords: "folder" },
      { char: "📂", keywords: "folder open" },
      { char: "✍️", keywords: "writing sign signature" },
      { char: "🖊️", keywords: "pen sign" },
      { char: "✅", keywords: "check done complete" },
      { char: "☑️", keywords: "checkbox done" },
      { char: "🔖", keywords: "bookmark label" },
      { char: "📌", keywords: "pin pinned" },
      { char: "📎", keywords: "paperclip attach" },
      { char: "🧾", keywords: "receipt invoice" },
    ],
  },
  {
    label: "Money",
    emojis: [
      { char: "💳", keywords: "card payment credit" },
      { char: "🏦", keywords: "bank ach" },
      { char: "💰", keywords: "money bag cash" },
      { char: "💵", keywords: "dollar cash money" },
      { char: "🪙", keywords: "coin money" },
      { char: "📊", keywords: "chart stats report" },
      { char: "📈", keywords: "growth chart up" },
      { char: "🧮", keywords: "calculator finance" },
      { char: "🏷️", keywords: "tag price" },
      { char: "🤝", keywords: "deal handshake agreement" },
    ],
  },
  {
    label: "Systems",
    emojis: [
      { char: "📶", keywords: "wifi signal network" },
      { char: "💡", keywords: "light bulb idea electric" },
      { char: "🌡️", keywords: "temperature thermostat" },
      { char: "❄️", keywords: "cold ac snow" },
      { char: "🔥", keywords: "heat fire furnace" },
      { char: "💧", keywords: "water drop plumbing" },
      { char: "🔌", keywords: "plug power electric" },
      { char: "🔧", keywords: "wrench repair tool" },
      { char: "🔨", keywords: "hammer build" },
      { char: "🧰", keywords: "toolbox tools" },
      { char: "🚰", keywords: "water tap" },
      { char: "🗑️", keywords: "trash waste bin" },
    ],
  },
  {
    label: "Travel & place",
    emojis: [
      { char: "📍", keywords: "location pin map" },
      { char: "🗺️", keywords: "map guide" },
      { char: "🧭", keywords: "compass guidebook directions" },
      { char: "📅", keywords: "calendar date schedule" },
      { char: "⏰", keywords: "clock time alarm" },
      { char: "🚗", keywords: "car parking" },
      { char: "✈️", keywords: "plane travel flight" },
      { char: "🧳", keywords: "luggage travel" },
      { char: "🌅", keywords: "sunrise morning" },
      { char: "🌴", keywords: "palm tropical vacation" },
    ],
  },
  {
    label: "People & welcome",
    emojis: [
      { char: "👋", keywords: "wave hello welcome" },
      { char: "🙌", keywords: "celebrate hands" },
      { char: "🎉", keywords: "party celebrate done" },
      { char: "🎁", keywords: "gift present welcome" },
      { char: "⭐", keywords: "star favorite rating" },
      { char: "❤️", keywords: "heart love" },
      { char: "👥", keywords: "people team owners" },
      { char: "🧑‍💼", keywords: "person business owner" },
      { char: "☕", keywords: "coffee breakfast" },
      { char: "🍷", keywords: "wine welcome drink" },
      { char: "🐾", keywords: "pet paw policy" },
      { char: "🔒", keywords: "lock secure private" },
    ],
  },
];

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emojis);
