/**
 * Searchable icon + emoji catalog for the IconPicker popover ONLY. Kept out of
 * the lean icon-picker-data module so list/card code that just resolves a stored
 * icon never bundles these keyword strings + the emoji set. Curated (not the full
 * Phosphor library) so the picker stays fast and the bundle small.
 */

import { ICON_BY_NAME, type PhosphorIcon } from "./icon-picker-data";

export type PhosphorEntry = { name: string; Icon: PhosphorIcon; keywords: string };

/** [name, keywords] pairs; the component is resolved from the shared map. */
const ICON_KEYWORDS: Array<[string, string]> = [
  // Documents
  ["FileText", "document file page text agreement"],
  ["File", "document file blank"],
  ["FilePdf", "pdf document file"],
  ["FileDoc", "doc word document file"],
  ["Files", "documents files stack"],
  ["Folder", "folder directory group"],
  ["Note", "note memo card"],
  ["NotePencil", "note edit write form"],
  ["ClipboardText", "clipboard form checklist intake"],
  ["Receipt", "receipt invoice bill"],
  ["Signature", "signature sign esign"],
  ["IdentificationCard", "id identity license w9 card"],
  ["SealCheck", "verified seal approved certified"],
  ["ShieldCheck", "shield insurance protection secure compliance"],
  ["Stamp", "stamp approve permit official"],
  ["FilePlus", "file new add create document"],
  ["FileMinus", "file remove delete document"],
  ["FileLock", "file secure private locked document"],
  ["FileMagnifyingGlass", "file search find document scan"],
  ["FileCsv", "csv spreadsheet export data file"],
  ["FileXls", "xls excel spreadsheet file"],
  ["FileZip", "zip archive compress file"],
  ["FileImage", "image photo file media"],
  ["FileArrowDown", "file download import receive"],
  ["FileArrowUp", "file upload export send"],
  ["Archive", "archive storage record history filed"],
  ["Clipboard", "clipboard task list form"],
  ["Invoice", "invoice billing charge statement"],
  ["Paperclip", "paperclip attach attachment"],
  ["PaperclipHorizontal", "paperclip attach horizontal"],
  ["Certificate", "certificate credential qualification award"],
  ["Gavel", "gavel legal court judge law"],
  ["Scales", "scales law legal compliance balance"],
  // Writing & editing
  ["Pen", "pen write sign edit"],
  ["PenNib", "pen ink write calligraphy"],
  ["Pencil", "pencil edit write draft"],
  ["PencilSimple", "pencil edit write"],
  ["PencilLine", "pencil underline edit text"],
  ["Eraser", "eraser erase delete clear"],
  ["Highlighter", "highlight mark annotate"],
  // Property & real estate
  ["House", "house home property rental"],
  ["HouseLine", "house home property"],
  ["HouseSimple", "house home simple property"],
  ["Buildings", "buildings property portfolio city"],
  ["BuildingApartment", "apartment condo unit building"],
  ["BuildingOffice", "office building commercial business"],
  ["Storefront", "storefront shop business"],
  ["Key", "key access lock checkin"],
  ["Door", "door entry access"],
  ["Bed", "bed bedroom sleep"],
  ["Bathtub", "bath bathroom tub"],
  ["Couch", "couch sofa living furniture"],
  ["Television", "tv television media"],
  ["Garage", "garage parking"],
  ["Bridge", "bridge location"],
  ["Armchair", "armchair chair seating living room"],
  ["Chair", "chair seat furniture"],
  ["Shower", "shower bathroom wash"],
  ["Toilet", "toilet bathroom restroom"],
  ["Oven", "oven kitchen cook appliance"],
  ["Lamp", "lamp light bedroom decor"],
  ["Towel", "towel bathroom amenity linen"],
  ["Rug", "rug carpet floor decor"],
  ["Table", "table dining furniture"],
  ["Desk", "desk workspace office furniture"],
  ["Dresser", "dresser bedroom furniture storage"],
  ["SwimmingPool", "pool swimming amenity outdoor"],
  ["Ruler", "ruler measure layout plan"],
  ["Screwdriver", "screwdriver repair maintenance tool"],
  // Finance & payment
  ["CreditCard", "card payment credit authorization"],
  ["Bank", "bank ach account payout"],
  ["Money", "money cash payment"],
  ["Coins", "coins money fee"],
  ["Wallet", "wallet payment balance"],
  ["ChartLine", "chart growth performance revenue"],
  ["ChartBar", "chart stats report"],
  ["ChartBarHorizontal", "chart horizontal stats report"],
  ["ChartPie", "pie chart breakdown distribution"],
  ["ChartDonut", "donut chart ring breakdown"],
  ["Graph", "graph analytics data trend"],
  ["Calculator", "calculator finance math"],
  ["Tag", "tag price label"],
  ["CurrencyDollar", "dollar currency usd money"],
  ["Cardholder", "cardholder wallet cards"],
  ["Percent", "percent discount fee rate tax"],
  // People & contacts
  ["Users", "people team owners guests"],
  ["User", "person owner guest user"],
  ["UserCircle", "profile person avatar"],
  ["UsersFour", "team group large crowd"],
  ["UsersThree", "team group people"],
  ["Person", "person individual single"],
  ["AddressBook", "contacts address book directory"],
  ["AddressBookTabs", "contacts book directory tabbed"],
  ["HandWaving", "welcome hello greeting onboarding"],
  ["Handshake", "deal agreement partner"],
  ["Smiley", "happy face smile"],
  // Communication
  ["Envelope", "email mail message"],
  ["EnvelopeOpen", "email open mail read"],
  ["Mailbox", "mailbox inbox mail receive"],
  ["Phone", "phone call contact"],
  ["PhoneCall", "phone call ringing active"],
  ["ChatCircle", "chat message comment"],
  ["ChatsCircle", "chats messages conversation"],
  ["ChatText", "chat text message talk"],
  ["ChatDots", "chat dots typing message"],
  ["Megaphone", "announce broadcast notice"],
  ["Bell", "bell notification reminder alert"],
  ["BellRinging", "bell ringing alert urgent notification"],
  ["BellSlash", "bell muted silent notification off"],
  ["BellZ", "bell snooze quiet do not disturb"],
  // Home systems & ops
  ["WifiHigh", "wifi internet network"],
  ["Lightbulb", "light idea electric"],
  ["Thermometer", "temperature thermostat hvac"],
  ["Snowflake", "cold ac cooling winter"],
  ["Fire", "heat fire furnace"],
  ["FireSimple", "fire heat flame simple"],
  ["FireExtinguisher", "extinguisher fire safety emergency"],
  ["Drop", "water plumbing leak"],
  ["Plugs", "power outlet electric"],
  ["Wrench", "repair maintenance fix tool"],
  ["Hammer", "build repair construction"],
  ["Toolbox", "tools maintenance setup"],
  ["Broom", "clean cleaning turnover"],
  ["PaintRoller", "paint decor renovate"],
  ["Lightning", "power energy fast action"],
  ["Pipe", "pipe plumbing water"],
  ["PipeWrench", "pipe wrench plumbing repair"],
  // Time & calendar
  ["Calendar", "calendar date schedule booking"],
  ["CalendarBlank", "calendar blank date empty"],
  ["CalendarCheck", "calendar done event complete booking"],
  ["CalendarPlus", "calendar add new event booking"],
  ["Clock", "time clock hours"],
  ["Alarm", "alarm wake time reminder"],
  ["Hourglass", "hourglass waiting pending time"],
  // Travel & location
  ["MapPin", "location address pin map"],
  ["MapTrifold", "map guide directions area"],
  ["Globe", "globe world international"],
  ["City", "city urban location downtown"],
  ["RoadHorizon", "road highway travel route"],
  ["Compass", "guide explore directions guidebook"],
  ["Car", "car parking transport"],
  ["Taxi", "taxi cab ride hail transport"],
  ["Bus", "bus public transport commute"],
  ["Train", "train rail transit commute"],
  ["Bicycle", "bicycle bike cycle green transport"],
  ["Boat", "boat water nautical marine"],
  ["Truck", "truck delivery transport moving"],
  ["Van", "van delivery vehicle shuttle"],
  ["Motorcycle", "motorcycle scooter transport"],
  ["Park", "park outdoor green area"],
  ["Anchor", "anchor dock port marina"],
  ["Airplane", "travel flight trip"],
  ["Suitcase", "luggage travel trip"],
  ["Footprints", "footprints walk trail path arrival"],
  // Celestial & weather
  ["Sun", "sun day weather"],
  ["SunHorizon", "sunrise sunset dawn dusk golden hour"],
  ["Moon", "night moon"],
  ["MoonStars", "night moon stars astronomy"],
  ["CloudSun", "partly cloudy weather mild"],
  ["CloudRain", "rain weather wet precipitation"],
  ["Rainbow", "rainbow color weather"],
  ["Campfire", "campfire fire outdoor camping warmth"],
  // Nature & greenery
  ["Tree", "tree nature outdoor"],
  ["TreePalm", "palm tree tropical vacation beach"],
  ["Leaf", "leaf nature eco green"],
  ["Plant", "plant garden nature"],
  ["Mountains", "mountains nature view"],
  ["Flower", "flower bloom garden spring"],
  ["FlowerLotus", "lotus flower zen spa wellness"],
  // Food & lifestyle
  ["ForkKnife", "food dining kitchen restaurant"],
  ["Coffee", "coffee cafe breakfast"],
  ["Wine", "wine drink welcome"],
  ["Bread", "bread bakery food bake"],
  ["Pizza", "pizza food takeout"],
  ["Cookie", "cookie snack treat baking"],
  ["Avocado", "avocado food healthy"],
  ["Carrot", "carrot vegetable food healthy"],
  ["Fish", "fish seafood food"],
  ["Orange", "orange fruit food"],
  ["Cake", "cake dessert celebration birthday"],
  ["Pepper", "pepper spice food kitchen"],
  ["ShoppingCart", "shopping supplies groceries"],
  ["Gift", "gift welcome present"],
  // Status & review
  ["Star", "star favorite rating review"],
  ["Heart", "heart love favorite"],
  ["Trophy", "trophy award win"],
  ["Target", "target goal focus"],
  ["Flag", "flag milestone mark"],
  ["FlagBanner", "flag banner milestone event"],
  ["Bookmark", "bookmark save"],
  ["Medal", "medal achievement award honor"],
  ["Crown", "crown premium top vip"],
  ["Diamond", "diamond premium luxury tier"],
  ["CheckCircle", "done complete approved check"],
  ["CheckFat", "check bold done complete"],
  ["Checks", "checks double done verified"],
  ["Warning", "warning alert caution"],
  ["Info", "info about details"],
  // Reference & learning
  ["Books", "books guide manual handbook"],
  ["Book", "book read manual guide"],
  ["BookOpen", "book open reading guide documentation"],
  ["GraduationCap", "education training onboarding"],
  ["Briefcase", "work business portfolio"],
  // Search & filter
  ["MagnifyingGlass", "search find look query"],
  ["Funnel", "filter funnel sort narrow"],
  ["FunnelSimple", "filter simple sort narrow"],
  ["SortAscending", "sort ascending order up"],
  ["SortDescending", "sort descending order down"],
  // Arrows & navigation
  ["ArrowUp", "up arrow navigate scroll"],
  ["ArrowDown", "down arrow navigate scroll"],
  ["ArrowLeft", "left arrow back navigate"],
  ["ArrowRight", "right arrow forward navigate"],
  ["ArrowClockwise", "refresh reload rotate clockwise"],
  ["ArrowCounterClockwise", "undo reset counter clockwise"],
  ["ArrowSquareOut", "external link open new window"],
  ["ArrowsOut", "expand fullscreen enlarge"],
  ["ArrowsIn", "collapse shrink minimize"],
  // Actions
  ["PlusCircle", "add plus new create"],
  ["XCircle", "close remove cancel delete x"],
  ["MinusCircle", "minus remove subtract"],
  ["DotsThree", "more options menu ellipsis horizontal"],
  ["DotsThreeVertical", "more options menu ellipsis vertical"],
  ["Question", "help question unknown support faq"],
  ["LinkSimple", "link url web connect"],
  ["Copy", "copy duplicate clone"],
  ["Upload", "upload send cloud push"],
  ["Download", "download receive pull get"],
  ["Share", "share send export distribute"],
  ["Trash", "delete trash remove bin"],
  ["TrashSimple", "delete trash remove"],
  // Media & devices
  ["Camera", "camera photo inspection"],
  ["Image", "image photo picture"],
  ["Laptop", "laptop computer portable device"],
  ["DeviceMobile", "mobile phone smartphone device"],
  ["DeviceTablet", "tablet ipad device"],
  ["Monitor", "monitor display screen"],
  ["Printer", "printer print paper output"],
  ["Headphones", "headphones audio listen music"],
  ["Microphone", "microphone record voice audio"],
  ["MusicNote", "music note audio song"],
  ["Barcode", "barcode scan sku inventory"],
  ["QrCode", "qr code scan link access"],
  ["Bluetooth", "bluetooth wireless connect pair"],
  ["Network", "network lan internet infrastructure"],
  // Security
  ["Lock", "lock secure private"],
  ["LockKey", "lock key secure access code"],
  ["Eye", "view seen preview"],
  // Gear & settings
  ["Gear", "settings config gear"],
  ["GearSix", "settings gear config system"],
  ["GearFine", "settings gear fine tune adjust"],
  ["Sliders", "settings controls adjust"],
  // Decorative / magic
  ["Sparkle", "ai magic sparkle generate"],
  ["Confetti", "celebrate done complete"],
  // Pets & animals
  ["PawPrint", "pet pets policy animal"],
  ["Dog", "dog pet animal"],
  ["Bird", "bird pet animal outdoor"],
  ["Cat", "cat pet feline animal"],
  ["Horse", "horse equine animal outdoor"],
  ["Butterfly", "butterfly nature insect garden"],
];

export const PHOSPHOR_ICONS: PhosphorEntry[] = ICON_KEYWORDS.map(([name, keywords]) => ({
  name,
  Icon: ICON_BY_NAME[name],
  keywords,
}));

export type EmojiEntry = { char: string; keywords: string };
export type EmojiGroup = { label: string; emojis: EmojiEntry[] };

/** Curated emoji set grouped by category — covers the property/ops domain. */
export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: "Property",
    emojis: [
      { char: "🏠", keywords: "house home property" },
      { char: "🏡", keywords: "house garden home" },
      { char: "🏘️", keywords: "houses neighborhood" },
      { char: "🏚️", keywords: "house old" },
      { char: "🏢", keywords: "building office" },
      { char: "🏨", keywords: "hotel rental" },
      { char: "🏖️", keywords: "beach vacation" },
      { char: "🛏️", keywords: "bed bedroom" },
      { char: "🛋️", keywords: "couch living" },
      { char: "🚪", keywords: "door entry" },
      { char: "🔑", keywords: "key access" },
      { char: "🗝️", keywords: "key old access" },
      { char: "🧹", keywords: "broom clean turnover" },
      { char: "🧽", keywords: "sponge clean" },
      { char: "🪑", keywords: "chair furniture" },
      { char: "🚿", keywords: "shower bathroom" },
    ],
  },
  {
    label: "Documents",
    emojis: [
      { char: "📄", keywords: "document page file" },
      { char: "📃", keywords: "document curl page" },
      { char: "📝", keywords: "memo form write" },
      { char: "📋", keywords: "clipboard checklist" },
      { char: "📑", keywords: "tabs bookmark documents" },
      { char: "🗂️", keywords: "folder dividers files" },
      { char: "📁", keywords: "folder" },
      { char: "📂", keywords: "folder open" },
      { char: "✍️", keywords: "writing sign signature" },
      { char: "🖊️", keywords: "pen sign" },
      { char: "✅", keywords: "check done complete" },
      { char: "☑️", keywords: "checkbox done" },
      { char: "🔖", keywords: "bookmark label" },
      { char: "📌", keywords: "pin pinned" },
      { char: "📎", keywords: "paperclip attach" },
      { char: "🧾", keywords: "receipt invoice" },
    ],
  },
  {
    label: "Money",
    emojis: [
      { char: "💳", keywords: "card payment credit" },
      { char: "🏦", keywords: "bank ach" },
      { char: "💰", keywords: "money bag cash" },
      { char: "💵", keywords: "dollar cash money" },
      { char: "🪙", keywords: "coin money" },
      { char: "📊", keywords: "chart stats report" },
      { char: "📈", keywords: "growth chart up" },
      { char: "🧮", keywords: "calculator finance" },
      { char: "🏷️", keywords: "tag price" },
      { char: "🤝", keywords: "deal handshake agreement" },
    ],
  },
  {
    label: "Systems",
    emojis: [
      { char: "📶", keywords: "wifi signal network" },
      { char: "💡", keywords: "light bulb idea electric" },
      { char: "🌡️", keywords: "temperature thermostat" },
      { char: "❄️", keywords: "cold ac snow" },
      { char: "🔥", keywords: "heat fire furnace" },
      { char: "💧", keywords: "water drop plumbing" },
      { char: "🔌", keywords: "plug power electric" },
      { char: "🔧", keywords: "wrench repair tool" },
      { char: "🔨", keywords: "hammer build" },
      { char: "🧰", keywords: "toolbox tools" },
      { char: "🚰", keywords: "water tap" },
      { char: "🗑️", keywords: "trash waste bin" },
    ],
  },
  {
    label: "Travel & place",
    emojis: [
      { char: "📍", keywords: "location pin map" },
      { char: "🗺️", keywords: "map guide" },
      { char: "🧭", keywords: "compass guidebook directions" },
      { char: "📅", keywords: "calendar date schedule" },
      { char: "⏰", keywords: "clock time alarm" },
      { char: "🚗", keywords: "car parking" },
      { char: "✈️", keywords: "plane travel flight" },
      { char: "🧳", keywords: "luggage travel" },
      { char: "🌅", keywords: "sunrise morning" },
      { char: "🌴", keywords: "palm tropical vacation" },
    ],
  },
  {
    label: "People & welcome",
    emojis: [
      { char: "👋", keywords: "wave hello welcome" },
      { char: "🙌", keywords: "celebrate hands" },
      { char: "🎉", keywords: "party celebrate done" },
      { char: "🎁", keywords: "gift present welcome" },
      { char: "⭐", keywords: "star favorite rating" },
      { char: "❤️", keywords: "heart love" },
      { char: "👥", keywords: "people team owners" },
      { char: "🧑‍💼", keywords: "person business owner" },
      { char: "☕", keywords: "coffee breakfast" },
      { char: "🍷", keywords: "wine welcome drink" },
      { char: "🐾", keywords: "pet paw policy" },
      { char: "🔒", keywords: "lock secure private" },
    ],
  },
];

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emojis);
