alter table public.parcel_team
  add column if not exists company_name text,
  add column if not exists hours text,
  add column if not exists services text[];

insert into public.parcel_team (
  id,
  name,
  company_name,
  role,
  location,
  website_url,
  instagram_url,
  member_since,
  hours,
  specialties,
  services,
  bio,
  active,
  founding_member,
  is_messageable,
  sort_order,
  updated_at
) values (
  '8c45457f-7e32-4b7f-9f7f-1a177eb5b2c1',
  'Belgica Perez',
  'BK Home Cleaning & Maintenance',
  'Cleaning Partner',
  'Tri-Cities and nearby areas',
  'https://bkhomecleaning.com',
  'https://instagram.com/bkhomecleaningwa',
  '2025-08',
  '8:00 AM to 5:30 PM',
  array[
    'Residential Cleaning',
    'Commercial Cleaning',
    'Deep Cleaning',
    'Recurring Cleaning',
    'Eco-Friendly Products',
    'Steam Disinfection',
    'Detail Cleaning',
    'Guest-Ready Homes'
  ]::text[],
  array[
    'Deep cleaning',
    'Monthly cleaning',
    'Twice-a-month cleaning',
    'Weekly or biweekly recurring plans',
    'Elderly home cleaning',
    'Newborn-care cleaning',
    'Organic product options',
    'Steam disinfection',
    'Windows',
    'Window tracks'
  ]::text[],
  'BK Home Cleaning & Maintenance provides professional residential and commercial cleaning across the Tri-Cities area. Their team focuses on reliable service, detailed work, and creating clean, safe, welcoming spaces for homeowners, guests, and businesses. They offer flexible cleaning plans and use high-quality products, with options for recurring cleanings, deep cleanings, eco-friendly products, steam disinfection, and special home-care needs.',
  true,
  false,
  false,
  50,
  now()
)
on conflict (id) do update set
  name = excluded.name,
  company_name = excluded.company_name,
  role = excluded.role,
  location = excluded.location,
  website_url = excluded.website_url,
  instagram_url = excluded.instagram_url,
  member_since = excluded.member_since,
  hours = excluded.hours,
  specialties = excluded.specialties,
  services = excluded.services,
  bio = excluded.bio,
  active = excluded.active,
  founding_member = excluded.founding_member,
  is_messageable = excluded.is_messageable,
  sort_order = excluded.sort_order,
  updated_at = excluded.updated_at;
