-- B2.1 (Stage 1, additive only): add nullable org_id to every org-owned table
-- that lacks it, plus an org_id index per table. Zero behavior change:
-- columns are nullable, no defaults yet, no policy changes.
-- Excluded: org layer tables (organizations, organization_members,
-- organization_branding, organization_settings), forms and document_templates
-- (already carry org_id; document_templates org_id stays nullable because
-- org_id = null means system template), and A3's reminder tables.

alter table public.activity_log add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_activity_log_org on public.activity_log(org_id);
alter table public.ai_insights add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_ai_insights_org on public.ai_insights(org_id);
alter table public.api_tokens add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_api_tokens_org on public.api_tokens(org_id);
alter table public.attachments add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_attachments_org on public.attachments(org_id);
alter table public.billing_catalog_items add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_catalog_items_org on public.billing_catalog_items(org_id);
alter table public.billing_credits add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_credits_org on public.billing_credits(org_id);
alter table public.billing_events add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_events_org on public.billing_events(org_id);
alter table public.billing_invoice_lines add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_invoice_lines_org on public.billing_invoice_lines(org_id);
alter table public.billing_invoices add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_invoices_org on public.billing_invoices(org_id);
alter table public.billing_payment_methods add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_payment_methods_org on public.billing_payment_methods(org_id);
alter table public.billing_profiles add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_profiles_org on public.billing_profiles(org_id);
alter table public.billing_refunds add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_refunds_org on public.billing_refunds(org_id);
alter table public.billing_schedule_lines add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_schedule_lines_org on public.billing_schedule_lines(org_id);
alter table public.billing_schedules add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_billing_schedules_org on public.billing_schedules(org_id);
alter table public.block_requests add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_block_requests_org on public.block_requests(org_id);
alter table public.bookings add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_bookings_org on public.bookings(org_id);
alter table public.changelogs add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_changelogs_org on public.changelogs(org_id);
alter table public.client_messages add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_client_messages_org on public.client_messages(org_id);
alter table public.communication_events add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_communication_events_org on public.communication_events(org_id);
alter table public.connections add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_connections_org on public.connections(org_id);
alter table public.contact_sources add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_contact_sources_org on public.contact_sources(org_id);
alter table public.contacts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_contacts_org on public.contacts(org_id);
alter table public.conversations add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_conversations_org on public.conversations(org_id);
alter table public.document_events add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_document_events_org on public.document_events(org_id);
alter table public.document_group_settings add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_document_group_settings_org on public.document_group_settings(org_id);
alter table public.document_properties add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_document_properties_org on public.document_properties(org_id);
alter table public.document_signers add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_document_signers_org on public.document_signers(org_id);
alter table public.documents add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_documents_org on public.documents(org_id);
alter table public.feedback_submissions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_feedback_submissions_org on public.feedback_submissions(org_id);
alter table public.finance_requests add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_finance_requests_org on public.finance_requests(org_id);
alter table public.form_responses add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_form_responses_org on public.form_responses(org_id);
alter table public.form_views add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_form_views_org on public.form_views(org_id);
alter table public.help_articles add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_help_articles_org on public.help_articles(org_id);
alter table public.help_categories add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_help_categories_org on public.help_categories(org_id);
alter table public.help_feedback add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_help_feedback_org on public.help_feedback(org_id);
alter table public.help_search_logs add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_help_search_logs_org on public.help_search_logs(org_id);
alter table public.inquiries add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_inquiries_org on public.inquiries(org_id);
alter table public.invoice_items add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_invoice_items_org on public.invoice_items(org_id);
alter table public.invoices add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_invoices_org on public.invoices(org_id);
alter table public.message_reads add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_message_reads_org on public.message_reads(org_id);
alter table public.messages add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_messages_org on public.messages(org_id);
alter table public.mfa_backup_codes add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_mfa_backup_codes_org on public.mfa_backup_codes(org_id);
alter table public.notes add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_notes_org on public.notes(org_id);
alter table public.notifications add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_notifications_org on public.notifications(org_id);
alter table public.onboarding_drafts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_onboarding_drafts_org on public.onboarding_drafts(org_id);
alter table public.owner_facts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_facts_org on public.owner_facts(org_id);
alter table public.owner_kyc add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_kyc_org on public.owner_kyc(org_id);
alter table public.owner_meetings add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_meetings_org on public.owner_meetings(org_id);
alter table public.owner_notes add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_notes_org on public.owner_notes(org_id);
alter table public.owner_notification_preferences add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_notification_preferences_org on public.owner_notification_preferences(org_id);
alter table public.owner_receipts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_receipts_org on public.owner_receipts(org_id);
alter table public.owner_setup_drafts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_setup_drafts_org on public.owner_setup_drafts(org_id);
alter table public.owner_tasks_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_tasks_legacy_org on public.owner_tasks_legacy(org_id);
alter table public.owner_timeline add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_owner_timeline_org on public.owner_timeline(org_id);
alter table public.payouts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_payouts_org on public.payouts(org_id);
alter table public.profiles add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_profiles_org on public.profiles(org_id);
alter table public.projects add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_projects_org on public.projects(org_id);
alter table public.properties add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_properties_org on public.properties(org_id);
alter table public.property_amenities add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_amenities_org on public.property_amenities(org_id);
alter table public.property_checklist_items add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_checklist_items_org on public.property_checklist_items(org_id);
alter table public.property_compliance add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_compliance_org on public.property_compliance(org_id);
alter table public.property_forms add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_forms_org on public.property_forms(org_id);
alter table public.property_owners add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_owners_org on public.property_owners(org_id);
alter table public.property_rules add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_rules_org on public.property_rules(org_id);
alter table public.property_setup_drafts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_setup_drafts_org on public.property_setup_drafts(org_id);
alter table public.property_task_templates add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_task_templates_org on public.property_task_templates(org_id);
alter table public.property_team add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_property_team_org on public.property_team(org_id);
alter table public.proxy_team add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_proxy_team_org on public.proxy_team(org_id);
alter table public.push_subscriptions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_push_subscriptions_org on public.push_subscriptions(org_id);
alter table public.receipt_audit_log add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_receipt_audit_log_org on public.receipt_audit_log(org_id);
alter table public.saved_views add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_saved_views_org on public.saved_views(org_id);
alter table public.session_log add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_session_log_org on public.session_log(org_id);
alter table public.setup_field_versions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_setup_field_versions_org on public.setup_field_versions(org_id);
alter table public.signed_documents add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_signed_documents_org on public.signed_documents(org_id);
alter table public.stripe_customers add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_stripe_customers_org on public.stripe_customers(org_id);
alter table public.subscriptions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_subscriptions_org on public.subscriptions(org_id);
alter table public.support_tickets add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_support_tickets_org on public.support_tickets(org_id);
alter table public.task_activity add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_activity_org on public.task_activity(org_id);
alter table public.task_assignees_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_assignees_legacy_org on public.task_assignees_legacy(org_id);
alter table public.task_comments add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_comments_org on public.task_comments(org_id);
alter table public.task_comments_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_comments_legacy_org on public.task_comments_legacy(org_id);
alter table public.task_label_map_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_label_map_legacy_org on public.task_label_map_legacy(org_id);
alter table public.task_labels add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_labels_org on public.task_labels(org_id);
alter table public.task_labels_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_labels_legacy_org on public.task_labels_legacy(org_id);
alter table public.task_subtasks_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_subtasks_legacy_org on public.task_subtasks_legacy(org_id);
alter table public.task_templates add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_templates_org on public.task_templates(org_id);
alter table public.task_templates_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_task_templates_legacy_org on public.task_templates_legacy(org_id);
alter table public.tasks add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_tasks_org on public.tasks(org_id);
alter table public.tasks_legacy add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_tasks_legacy_org on public.tasks_legacy(org_id);
alter table public.tax_profiles add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_tax_profiles_org on public.tax_profiles(org_id);
alter table public.treasury_accounts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_accounts_org on public.treasury_accounts(org_id);
alter table public.treasury_alerts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_alerts_org on public.treasury_alerts(org_id);
alter table public.treasury_audit_log add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_audit_log_org on public.treasury_audit_log(org_id);
alter table public.treasury_balance_snapshots add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_balance_snapshots_org on public.treasury_balance_snapshots(org_id);
alter table public.treasury_connections add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_connections_org on public.treasury_connections(org_id);
alter table public.treasury_forecasts add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_forecasts_org on public.treasury_forecasts(org_id);
alter table public.treasury_savings_goals add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_savings_goals_org on public.treasury_savings_goals(org_id);
alter table public.treasury_subscriptions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_subscriptions_org on public.treasury_subscriptions(org_id);
alter table public.treasury_transactions add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_treasury_transactions_org on public.treasury_transactions(org_id);
alter table public.vendor_properties add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_vendor_properties_org on public.vendor_properties(org_id);
alter table public.vendors add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_vendors_org on public.vendors(org_id);
alter table public.w9_access_log add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_w9_access_log_org on public.w9_access_log(org_id);
alter table public.workspace_request_attachments add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_workspace_request_attachments_org on public.workspace_request_attachments(org_id);
alter table public.workspace_request_items add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_workspace_request_items_org on public.workspace_request_items(org_id);
alter table public.workspace_request_recipients add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_workspace_request_recipients_org on public.workspace_request_recipients(org_id);
alter table public.workspace_requests add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_workspace_requests_org on public.workspace_requests(org_id);
alter table public.workspaces add column if not exists org_id uuid references public.organizations(id);
create index if not exists idx_workspaces_org on public.workspaces(org_id);

-- forms and document_templates already have org_id; ensure they are indexed too.
create index if not exists idx_forms_org on public.forms(org_id);
create index if not exists idx_document_templates_org on public.document_templates(org_id);
